import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const codersCrux = localFont({ 
  src: './fonts/CodersCrux.ttf',  // Correct path from layout.tsx to fonts folder
  variable: '--font-coders-crux'
});
export const metadata: Metadata = {
  title: "Rupture Labs",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",  // Add path to favicon here
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scrollbar-thin scrollbar-track-rounded-full scrollbar-thumb-rounded-full scrollbar-thumb-white scrollbar-track-black " lang="en">
      <body
        className={`${geistSans.variable}  ${codersCrux.variable} ${geistMono.variable} antialiased `}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
